version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/tufin/sabik
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: script/testcov.sh
      - run:
          name: Upload coverage results
          command:
            bash <(curl -s https://codecov.io/bash)