version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/tufin/sabik
    steps:
      - checkout
      - run:
          name: Test
          command: |
            go get -v -t -d ./...
            ./script/testcov.sh
            bash <(curl -s https://codecov.io/bash)